### ISSUE TITLE
Publish wheels for Python 3.8

### ISSUE THREAD

**Issue by lidalei** [stan-dev/pystan-wheels#20]
Hi, I am using pystan in Python 3.8. It needs to build from source, which is a slow process. Could you publish the wheels for Python 3.8 to Pypi https://pypi.org/project/pystan/#files? Thanks!

**Comment by chaitan94** [comment]
Looks like it is a work in progress: https://github.com/stan-dev/pystan-wheels/pull/19

**Comment by lidalei** [comment]
The wheels for Python 3.8 was released hours ago (https://pypi.org/project/pystan/#files). So I will close the issue. Thx!
