### ISSUE TITLE
Retrieve wheels (problem with wheelhouse uploader)

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/pystan-wheels#5]
macos builds are finishing but the wheel is not ending up on rackspace.

Perhaps we should try out travis-ci's native support for Rackspace cloudfiles: https://docs.travis-ci.com/user/deployment/cloudfiles/

**Comment by ahartikainen** [comment]
Their names a bit weird

`pystan-2.18.0.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl`

**Comment by ahartikainen** [comment]
https://d36102825770f036e7f0-25e1da3ee193e97cce4726db07962f5d.ssl.cf5.rackcdn.com

At least they all are there, including win-wheels.

**Comment by ahartikainen** [comment]
`download_wheels.sh` should have `cp27` and `cp37` for windows if we want to upload them to pypi.

**Comment by riddell-stan** [comment]
You're right. They are there now. The macOS wheels were not showing up before. And it still looks like the wheelhouse uploader is failing on these builds:

https://travis-ci.org/stan-dev/pystan-wheels/builds/421273111

**Comment by ahartikainen** [comment]
Based on the dates, upload is successful, but there are some problems when it exiting the line it fails somehow. Is there a way to make it verbose?

**Comment by ahartikainen** [comment]
Would `travis wait` help? Or is it just getting stuck?

**Comment by riddell-stan** [comment]
It seems to be getting stuck. Uploading, when it works, takes 9 seconds.

Somehow they are getting uploaded. Maybe it's refusing to overwrite an existing file?

I'll close this for now. I managed to upload all the wheels to pypi.

**Comment by ahartikainen** [comment]
I was thinking too, it might be overwrite problem.
